this is the python exception task
